# Generated by Django 4.0.1 on 2022-02-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('matricula', models.CharField(max_length=10, verbose_name='Matrícula')),
                ('idade', models.PositiveSmallIntegerField(default=0, verbose_name='Idade')),
                ('nasc', models.DateTimeField(verbose_name='Data de Nascimento')),
                ('situacao', models.CharField(choices=[('1', 'Matriculado'), ('2', 'Trancado'), ('3', 'Cancelado')], default='2', max_length=10, verbose_name='Situação')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('mediaGeral', models.PositiveSmallIntegerField(default=0, verbose_name='Média Geral')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Curso')),
                ('totalCreditos', models.CharField(max_length=4, verbose_name='Total de Créditos')),
                ('coordenador', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Disciplina')),
                ('creditos', models.CharField(max_length=2, verbose_name='Créditos')),
                ('limiteFalta', models.CharField(max_length=3, verbose_name='Limite de Faltas')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome do Aluno')),
                ('totalCreditos', models.CharField(max_length=10, verbose_name='Total de Créditos')),
                ('curso', models.CharField(max_length=10, verbose_name='Nome do Curso')),
                ('disciplina', models.CharField(max_length=120, verbose_name='Disciplina Cursada')),
                ('mediaDisciplina', models.PositiveSmallIntegerField(default=0, verbose_name='Média da Disciplina')),
                ('nota1', models.PositiveSmallIntegerField(default=0, verbose_name='Nota Primerio Semestre')),
                ('nota2', models.PositiveSmallIntegerField(default=0, verbose_name='Nota Segundo Semestre')),
                ('mediaGeral', models.PositiveSmallIntegerField(default=0, verbose_name='Média Geral do Aluno')),
                ('situacao', models.CharField(choices=[('1', 'Aprovado'), ('2', 'Reprovado')], default='1', max_length=10, verbose_name='Situação')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('semestre', models.CharField(max_length=10)),
                ('matriculaAluno', models.CharField(max_length=10, verbose_name='Matrícula do Aluno')),
                ('codDisciplina', models.CharField(max_length=10, verbose_name='Código da Disciplina')),
                ('nota1', models.CharField(max_length=4, verbose_name='Nota 1')),
                ('nota2', models.CharField(max_length=4, verbose_name='Nota 2')),
                ('falta1', models.CharField(max_length=4, verbose_name='Falta 1')),
                ('falta2', models.CharField(max_length=4, verbose_name='Falta 2')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('semestre', models.CharField(max_length=10)),
                ('dataInicio', models.DateField(verbose_name='Data de Início')),
                ('dataFim', models.DateField(verbose_name='Data de Término')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('matricula', models.CharField(max_length=10, verbose_name='Matrícula')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('semestre', models.DateField(blank=True, null=True)),
                ('disciplina', models.CharField(max_length=120)),
                ('numeroVagas', models.CharField(max_length=3, verbose_name='Número de Vagas')),
                ('professor', models.CharField(max_length=50)),
            ],
        ),
    ]
